In [4]:
#Simple Linear Regression
from sklearn.linear_model import LinearRegression
import numpy as np

# Example dataset
size = np.array([1500, 1700, 1800, 2000, 2300]).reshape(-1, 1)  # House sizes (sq ft)
price = np.array([300000, 340000, 360000, 400000, 460000])  # Prices in dollars

# Create and fit the model
model = LinearRegression()
model.fit(size, price)

# Predict the price for a 2500 sq ft house
predicted_price = model.predict(np.array([[2500]]))
predicted_price  # Result in dollars


array([500000.])

In [5]:
#multiple linear regression
from sklearn.linear_model import LinearRegression
import numpy as np

# Example dataset
features = np.array([[1500, 3], [1700, 3], [1800, 4], [2000, 4], [2300, 5]])  # Size and bedrooms
price = np.array([300000, 340000, 360000, 400000, 460000])  # Prices in dollars

# Create and fit the model
model = LinearRegression()
model.fit(features, price)

# Predict the price for a 2500 sq ft house with 4 bedrooms
predicted_price = model.predict(np.array([[2500, 4]]))
predicted_price  # Result in dollars


array([500000.])

In [6]:
#polynomial regression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

# Example dataset
experience = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # Years of experience
profit = np.array([40000, 50000, 65000, 80000, 105000])  # Profit in dollars

# Transform the data to include polynomial features
poly = PolynomialFeatures(degree=2)  # 2nd degree polynomial
experience_poly = poly.fit_transform(experience)

# Create and fit the model
model = LinearRegression()
model.fit(experience_poly, profit)

# Predict profit for 6 years of experience
predicted_profit = model.predict(poly.transform(np.array([[6]])))
predicted_profit  # Result in dollars


array([131000.])

In [8]:
from sklearn.metrics import mean_absolute_error

# Actual vs. predicted values
actual = [150, 200, 250, 300, 350]
predicted = [148, 210, 240, 305, 360]

# Calculate MAE
mae = mean_absolute_error(actual, predicted)
mae  # Result: Mean absolute error value


7.4

In [9]:
from sklearn.metrics import mean_squared_error

# Actual vs. predicted values
actual = [150, 200, 250, 300, 350]
predicted = [148, 210, 240, 305, 360]

# Calculate MSE
mse = mean_squared_error(actual, predicted)
mse  # Result: Mean squared error value


65.8

In [10]:
from sklearn.metrics import r2_score

# Actual vs. predicted values
actual = [150, 200, 250, 300, 350]
predicted = [148, 210, 240, 305, 360]

# Calculate R-squared
r_squared = r2_score(actual, predicted)
r_squared  # Result: R-squared value


0.98684

In [7]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Actual and predicted values
actual = [150, 200, 250, 300, 350]
predicted = [148, 210, 240, 305, 360]

# Calculate all three metrics
mae = mean_absolute_error(actual, predicted)
mse = mean_squared_error(actual, predicted)
r_squared = r2_score(actual, predicted)

# Output results
mae, mse, r_squared  # Display MAE, MSE, and R-squared values


(7.4, 65.8, 0.98684)